### ISSUE TITLE
您另一个项目下面的r2s的minimal固件插usb无线网卡会死机

### ISSUE THREAD

**Issue by Benjamin23333** [klever1988/openwrt-autobuild#1]
这个问题本来应该反应到那个对应，项目下面的，但是那个项目的issues不知道为什么关掉了，事情是这样的，我昨天刷了四月五日的minimal，插着usb无线网卡开机，风扇一直转，也没接到无线信号，我就把无线网卡拔了，接上网线，能连上了，我没多想，以为只是重启就解决了的问题，本来无线网卡也只是我方便设置搞的，也没再插上去。
今天，我刷四月六日的版本，还是插着无线网卡，想用手机设置方便点，但是出现了一样的状况，我反复试验，包括插着网卡启动（会出现上面出现了状况）；启动后插上usb无线（会当场死机，luci界面无反应），都说明死机的凶手是无线网卡，请问这是bug么？

**Comment by Benjamin23333** [comment]
今天我又做了实验，发现minimal和lean版会死机，lienol版有无线引号，但是连不上，一直在获取ip地址，我还试了友善官方的固件，可以使用usb无线网卡，顺便说一句，我是用的您推荐的comfast 811ac

**Comment by Yohoa** [comment]
同样关注使用无线网路卡的问题，希望听到后续进展:D

**Comment by stupidloud** [comment]
用新版的固件就不会了 去掉了mac80211的升级就不会卡无线了
